/** Declaration file generated by dts-gen */

export class GpsOnly {
    constructor();

    coordenate(success: any, failure: any): void;

}

export namespace GpsOnly {
    namespace prototype {
        function coordenate(success: any, failure: any): void;

        namespace coordenate {
            const prototype: {
            };

        }

    }

}

